name: Deployment

on:
  push:
    branches:
      - main  # Adjust this branch name as per your requirements

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to UAT
        uses: salesforcedx/sfpowerscripts@v3
        with:
          command: deploy
          args: -p $(git diff-tree --no-commit-id --name-only --diff-filter=AM -r ${{ github.sha }} | tr '\n' ',' | sed 's/,$//') -u <INTEG>
        env:
          SFDX_AUTOUPDATE_DISABLE: true
