name: Deployment

on:
  push:
    branches:
      - main  # Adjust this branch name as per your requirements

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Salesforce CLI
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Deploy to UAT
        run: |
          commitSHA=$(git rev-parse HEAD)
          files=$(git diff-tree --no-commit-id --name-only --diff-filter=AM -r $commitSHA | tr '\n' ',' | sed 's/,$//')
          echo "Modified Files:"
          git diff-tree --no-commit-id --name-only -r $commitSHA
          echo "+++++++++++++"
          echo "$files"
          sfdx force:source:deploy -p "$files" -u "INTEG"
