name: Deployment

on:
  push:
    branches:
      - main  # Adjust this branch name as per your requirements

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Salesforce CLI
        run: |
          curl https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz | tar xJf -
          ./sfdx/install

      - name: Set up Salesforce CLI
        run: sfdx update

      - name: Deploy to UAT
        run: |
          commitSHA=$(git rev-parse HEAD)
          files=$(git diff-tree --no-commit-id --name-only --diff-filter=AM -r $commitSHA | tr '\n' ',' | sed 's/,$//')
          echo "Modified Files:"
          git diff-tree --no-commit-id --name-only -r $commitSHA
          echo "+++++++++++++"
          echo "$files"
          sfdx force:source:deploy -p "$files" -u "INTEG"

